name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    tags:
      - 'ver/*' # Changed: Now matches tags like 'ver/1.2.3'
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set image version
        id: set_version
        run: |
          VERSION_REF_NAME=${{ github.ref_name }}

          # Check if the trigger is a tag push matching the 'ver/...' pattern
          if [[ "${{ github.ref }}" == refs/tags/ver/* ]]; then
            # Strip the 'ver/' prefix from the tag name (e.g., 'ver/1.2.3' -> '1.2.3')
            # The bash substitution ${variable#prefix} handles this cleanly.
            PARSED_VERSION="${VERSION_REF_NAME#ver/}"
            
            echo "IMAGE_VERSION=$PARSED_VERSION" >> $GITHUB_ENV
            echo "ROLLING_VERSION=latest" >> $GITHUB_ENV
          else
            # For pushes to 'main' branch or pull requests
            echo "IMAGE_VERSION=$(date +%s)" >> $GITHUB_ENV
            echo "ROLLING_VERSION=develop" >> $GITHUB_ENV
          fi

      - name: Set lowercase repository name
        id: repo_name_lower
        run: echo "REPO_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Docker image
        run: docker build . --file Dockerfile-bookworm --tag ghcr.io/${{ env.REPO_LOWER }}-bookworm:${{ env.IMAGE_VERSION }} --tag ghcr.io/${{ env.REPO_LOWER }}-bookworm:${{ env.ROLLING_VERSION }}

      - name: Push Docker image
        if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/'))
        run: docker push --all-tags ghcr.io/${{ env.REPO_LOWER }}-bookworm
